import { Product, Category, FAQItem } from "@/types";

export const categories: Category[] = [
  {
    id: "1",
    name: "Hiburan",
    slug: "hiburan",
    description: "Streaming film, musik, dan konten premium",
    icon: "Film",
    count: 3,
    accentColor: "from-red-500 to-orange-500",
    products: ["netflix", "youtube-premium", "spotify"],
  },
  {
    id: "2",
    name: "AI Tools",
    slug: "ai-tools",
    description: "Asisten AI premium untuk produktivitas",
    icon: "Brain",
    count: 3,
    accentColor: "from-emerald-500 to-cyan-500",
    products: ["chatgpt-plus", "gemini-ai", "grok-super"],
  },
  {
    id: "3",
    name: "Developer",
    slug: "developer",
    description: "Tools dan resource untuk developer",
    icon: "Code2",
    count: 4,
    accentColor: "from-blue-500 to-indigo-500",
    products: ["github-copilot-pro", "github-student", "windsurf-pro", "digitalocean-vcc"],
  },
  {
    id: "4",
    name: "Social Premium",
    slug: "social-premium",
    description: "Upgrade akun sosial media",
    icon: "Users",
    count: 4,
    accentColor: "from-violet-500 to-purple-500",
    products: ["x-twitter-account", "twitter-verified", "telegram-premium", "discord-nitro"],
  },
  {
    id: "5",
    name: "Produktivitas",
    slug: "produktivitas",
    description: "Tools desain dan produktivitas",
    icon: "Palette",
    count: 1,
    accentColor: "from-cyan-500 to-blue-500",
    products: ["canva"],
  },
  {
    id: "6",
    name: "Security",
    slug: "security",
    description: "Keamanan dan privasi online",
    icon: "Shield",
    count: 1,
    accentColor: "from-teal-500 to-green-500",
    products: ["vpn"],
  },
];

export const products: Product[] = [
  {
    id: "1",
    slug: "netflix",
    name: "Netflix",
    shortDesc: "Akses streaming premium untuk film dan series favorit.",
    description: "Nikmati ribuan film, series, dan dokumenter premium dari Netflix. Streaming tanpa batas di semua perangkat dengan kualitas terbaik.",
    price: 54000,
    originalPrice: 65000,
    category: "hiburan",
    tags: ["Streaming", "Film", "Series"],
    rating: 4.9,
    reviews: 2340,
    sales: 8921,
    featured: true,
    badge: "Populer",
    delivery: "Aktivasi 5-15 menit",
    accentColor: "#E50914",
    iconBg: "from-red-600 to-red-800",
  },
  {
    id: "2",
    slug: "youtube-premium",
    name: "YouTube Premium",
    shortDesc: "Nonton tanpa iklan, background play, dan YouTube Music.",
    description: "YouTube tanpa iklan, putar video di background, download offline, dan akses penuh YouTube Music Premium.",
    price: 32000,
    category: "hiburan",
    tags: ["Streaming", "Musik", "Video"],
    rating: 4.8,
    reviews: 1856,
    sales: 7234,
    featured: true,
    badge: "Terlaris",
    delivery: "Aktivasi 5-15 menit",
    accentColor: "#FF0000",
    iconBg: "from-red-500 to-red-700",
  },
  {
    id: "3",
    slug: "chatgpt-plus",
    name: "ChatGPT Plus",
    shortDesc: "Akses fitur premium ChatGPT untuk produktivitas harian.",
    description: "Akses GPT-4o, DALL-E, Advanced Data Analysis, dan fitur premium lainnya. Ideal untuk riset, coding, dan writing.",
    price: 135000,
    originalPrice: 160000,
    category: "ai-tools",
    tags: ["AI", "Produktivitas", "Writing"],
    rating: 4.9,
    reviews: 3120,
    sales: 12450,
    featured: true,
    badge: "Populer",
    delivery: "Aktivasi 5-15 menit",
    accentColor: "#10A37F",
    iconBg: "from-emerald-600 to-emerald-800",
  },
  {
    id: "4",
    slug: "digitalocean-vcc",
    name: "DigitalOcean VCC $200 Balance",
    shortDesc: "Cloud credit untuk deploy project, server, dan testing.",
    description: "Virtual Credit Card dengan saldo $200 untuk DigitalOcean. Cocok untuk deploy project, hosting, dan testing server cloud.",
    price: 85000,
    category: "developer",
    tags: ["Cloud", "Server", "VCC"],
    rating: 4.7,
    reviews: 892,
    sales: 3456,
    featured: true,
    badge: "Limited",
    delivery: "Pengiriman instan",
    accentColor: "#0080FF",
    iconBg: "from-blue-500 to-blue-700",
  },
  {
    id: "5",
    slug: "canva",
    name: "Canva",
    shortDesc: "Desain premium untuk konten, brand, dan presentasi.",
    description: "Akses penuh Canva Pro dengan jutaan template, elemen premium, background remover, dan fitur kolaborasi tim.",
    price: 45000,
    originalPrice: 55000,
    category: "produktivitas",
    tags: ["Desain", "Template", "Brand"],
    rating: 4.8,
    reviews: 2100,
    sales: 6789,
    featured: true,
    badge: "Promo",
    delivery: "Aktivasi 5-15 menit",
    accentColor: "#00C4CC",
    iconBg: "from-cyan-500 to-purple-500",
  },
  {
    id: "6",
    slug: "discord-nitro",
    name: "Discord Nitro",
    shortDesc: "Boost pengalaman Discord dengan fitur premium.",
    description: "Upload file lebih besar, emoji custom di semua server, profil animated, streaming HD, dan 2x server boost.",
    price: 42000,
    category: "social-premium",
    tags: ["Gaming", "Social", "Chat"],
    rating: 4.7,
    reviews: 1560,
    sales: 5432,
    featured: true,
    badge: "Instan",
    delivery: "Pengiriman instan",
    accentColor: "#5865F2",
    iconBg: "from-indigo-500 to-indigo-700",
  },
  {
    id: "7",
    slug: "gemini-ai",
    name: "Gemini AI",
    shortDesc: "Asisten AI premium untuk riset, writing, dan workflow.",
    description: "Akses Gemini Advanced dengan model terbaru dari Google. Ideal untuk analisis data, riset mendalam, dan kreasi konten.",
    price: 125000,
    category: "ai-tools",
    tags: ["AI", "Google", "Riset"],
    rating: 4.6,
    reviews: 780,
    sales: 2345,
    featured: true,
    badge: "Baru",
    delivery: "Aktivasi 5-15 menit",
    accentColor: "#4285F4",
    iconBg: "from-blue-500 to-violet-500",
  },
  {
    id: "8",
    slug: "vpn",
    name: "VPN Premium",
    shortDesc: "Akses aman dan privat untuk browsing harian.",
    description: "VPN premium dengan 5000+ server di 60 negara. Kecepatan tinggi, no-log policy, dan proteksi lengkap untuk semua perangkat.",
    price: 28000,
    category: "security",
    tags: ["Security", "Privacy", "Network"],
    rating: 4.7,
    reviews: 1230,
    sales: 4567,
    featured: false,
    badge: "Ready",
    delivery: "Pengiriman instan",
    accentColor: "#22C55E",
    iconBg: "from-green-500 to-teal-600",
  },
  {
    id: "9",
    slug: "x-twitter-account",
    name: "X / Twitter Account",
    shortDesc: "Akun X/Twitter siap pakai sesuai kebutuhan.",
    description: "Akun X/Twitter fresh dan siap pakai. Cocok untuk personal branding, marketing, atau kebutuhan bisnis.",
    price: 35000,
    category: "social-premium",
    tags: ["Social Media", "Marketing", "Branding"],
    rating: 4.5,
    reviews: 670,
    sales: 2890,
    featured: false,
    badge: "Ready",
    delivery: "Pengiriman instan",
    accentColor: "#000000",
    iconBg: "from-gray-700 to-gray-900",
  },
  {
    id: "10",
    slug: "grok-super",
    name: "Grok Super",
    shortDesc: "Akses Grok premium untuk eksplorasi AI terbaru.",
    description: "Akses Grok Super dari xAI dengan kemampuan real-time search, image generation, dan analisis mendalam.",
    price: 145000,
    category: "ai-tools",
    tags: ["AI", "xAI", "Search"],
    rating: 4.5,
    reviews: 430,
    sales: 1234,
    featured: false,
    badge: "Limited",
    delivery: "Aktivasi 5-15 menit",
    accentColor: "#FF6B35",
    iconBg: "from-orange-500 to-red-600",
  },
  {
    id: "11",
    slug: "twitter-verified",
    name: "Twitter Verified / Blue Check",
    shortDesc: "Layanan verifikasi/centang biru sesuai ketentuan produk.",
    description: "Dapatkan centang biru (verified badge) untuk akun X/Twitter kamu. Tingkatkan kredibilitas dan jangkauan konten.",
    price: 95000,
    category: "social-premium",
    tags: ["Verified", "Social Media", "Branding"],
    rating: 4.6,
    reviews: 560,
    sales: 1890,
    featured: true,
    badge: "Premium",
    delivery: "Aktivasi 1-24 jam",
    accentColor: "#1D9BF0",
    iconBg: "from-blue-400 to-blue-600",
  },
  {
    id: "12",
    slug: "telegram-premium",
    name: "Telegram Premium",
    shortDesc: "Nikmati fitur premium Telegram untuk akun utama.",
    description: "Upload file hingga 4GB, stiker premium, kecepatan download lebih cepat, voice-to-text, dan fitur eksklusif lainnya.",
    price: 38000,
    category: "social-premium",
    tags: ["Messaging", "Social", "Premium"],
    rating: 4.7,
    reviews: 980,
    sales: 4321,
    featured: true,
    badge: "Instan",
    delivery: "Pengiriman instan",
    accentColor: "#26A5E4",
    iconBg: "from-sky-500 to-blue-600",
  },
  {
    id: "13",
    slug: "github-student",
    name: "GitHub Student",
    shortDesc: "Paket benefit developer untuk belajar dan membangun project.",
    description: "GitHub Student Developer Pack dengan akses ke 100+ tools premium termasuk Copilot, domain gratis, cloud credits, dan lainnya.",
    price: 65000,
    category: "developer",
    tags: ["GitHub", "Student", "DevTools"],
    rating: 4.8,
    reviews: 1450,
    sales: 5678,
    featured: true,
    badge: "Populer",
    delivery: "Aktivasi 1-24 jam",
    accentColor: "#24292F",
    iconBg: "from-gray-700 to-gray-900",
  },
  {
    id: "14",
    slug: "spotify",
    name: "Spotify",
    shortDesc: "Streaming musik premium tanpa iklan.",
    description: "Dengarkan musik tanpa iklan, download lagu offline, kualitas audio tinggi, dan skip unlimited di semua perangkat.",
    price: 27000,
    category: "hiburan",
    tags: ["Musik", "Streaming", "Audio"],
    rating: 4.9,
    reviews: 2890,
    sales: 9876,
    featured: true,
    badge: "Terlaris",
    delivery: "Pengiriman instan",
    accentColor: "#1DB954",
    iconBg: "from-green-500 to-green-700",
  },
  {
    id: "15",
    slug: "windsurf-pro",
    name: "Windsurf Pro",
    shortDesc: "AI coding assistant premium untuk workflow developer.",
    description: "AI coding assistant dari Codeium dengan autocomplete cerdas, chat AI, dan integrasi editor. Tingkatkan produktivitas coding.",
    price: 110000,
    category: "developer",
    tags: ["AI", "Coding", "IDE"],
    rating: 4.6,
    reviews: 340,
    sales: 1567,
    featured: false,
    badge: "Baru",
    delivery: "Aktivasi 5-15 menit",
    accentColor: "#06B6D4",
    iconBg: "from-cyan-500 to-teal-600",
  },
  {
    id: "16",
    slug: "github-copilot-pro",
    name: "GitHub Copilot Pro",
    shortDesc: "Pair programmer AI langsung di editor favoritmu.",
    description: "GitHub Copilot Pro dengan suggestion cerdas, chat, dan code review AI. Support VS Code, JetBrains, Neovim, dan lainnya.",
    price: 95000,
    originalPrice: 120000,
    category: "developer",
    tags: ["AI", "GitHub", "Coding"],
    rating: 4.8,
    reviews: 1670,
    sales: 6543,
    featured: true,
    badge: "Populer",
    delivery: "Aktivasi 5-15 menit",
    accentColor: "#24292F",
    iconBg: "from-gray-600 to-gray-800",
  },
];

export const faqItems: FAQItem[] = [
  {
    question: "Berapa lama proses aktivasi produk?",
    answer: "Sebagian besar produk diproses dalam 5-15 menit setelah pembayaran dikonfirmasi. Beberapa produk premium mungkin memerlukan waktu hingga 1-24 jam untuk aktivasi manual oleh tim kami.",
  },
  {
    question: "Apakah produk bergaransi?",
    answer: "Ya, semua produk di Nebuna Store dilengkapi garansi replacement. Jika produk bermasalah dalam masa garansi, kami akan mengganti tanpa biaya tambahan.",
  },
  {
    question: "Bagaimana jika produk bermasalah?",
    answer: "Hubungi tim support kami melalui WhatsApp atau live chat 24/7. Kami akan membantu menyelesaikan masalah atau memberikan replacement sesuai kebijakan garansi.",
  },
  {
    question: "Metode pembayaran apa saja yang tersedia?",
    answer: "Kami menerima QRIS, transfer bank (BCA, BNI, BRI, Mandiri), e-wallet (GoPay, OVO, DANA, ShopeePay), dan pembayaran di gerai retail (Alfamart, Indomaret).",
  },
  {
    question: "Apakah bisa lacak pesanan?",
    answer: "Ya, setelah checkout kamu akan mendapatkan nomor pesanan. Gunakan fitur Lacak Pesanan di website atau hubungi support untuk cek status terbaru.",
  },
  {
    question: "Apakah akun/produk langsung dikirim?",
    answer: "Produk dengan label 'Pengiriman instan' akan dikirim otomatis setelah pembayaran. Produk lainnya diproses oleh tim dan dikirim melalui email atau chat.",
  },
];
